name = "CBX"
uuid = "395ff7de-eab4-4c3d-8b08-1558ec221b6c"
authors = ["Rafael Bailo"]
version = "1.0.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.8"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JuliaFormatter", "SafeTestsets", "Test"]
